[default]
workshop = [
    "450814997", # CBA_A3's Workshop ID
	"463939057"  # ACE3's Workshop ID
]
parameters=[
	# It's not possible to use a variable, you will have to change this path to your actual path
	"-mod=\"C:\\Users\\julien\\source\\repos\\jetelain\\cTab\\@cTab\\.hemttout\\dev\"" 
]
mission = "basic.VR"
