name = "cTab IRL"
prefix = "ctab_irl"
author = "cTab Authors, see https://github.com/jetelain/cTab"
template = "cba"
mainprefix = "z"
folder_optionals = false
sig_version = 3

[version]
path = "addons/main/script_version.hpp"
git_hash = 0

[files]
include = [
    "mod.cpp",
    "*.dll",
    "icon_ctab_irl.paa"
]
