#define IDC_TECHNICALDATA_TITLE 8734
#define IDC_TECHNICALDATA_CALLSIGNLABEL 8735
#define IDC_TECHNICALDATA_CALLSIGN 9135
#define IDC_TECHNICALDATA_OKBUTTON 1
#define IDC_TECHNICALDATA_CANCELBUTTON 2
#define IDC_TECHNICALDATA_FRAME  9935

#define IDD_TECHNICALDATA 1775148