//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cTabWebApp {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResource() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("cTabWebApp.SharedResource", typeof(SharedResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Arma is not yet connected. Please wait for key to be available in-game..
        /// </summary>
        public static string ArmaNotYetConnected {
            get {
                return ResourceManager.GetString("ArmaNotYetConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Contact.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Disconnect.
        /// </summary>
        public static string Disconnect {
            get {
                return ResourceManager.GetString("Disconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Download mod.
        /// </summary>
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Go back to {0}.
        /// </summary>
        public static string GoBackTo {
            get {
                return ResourceManager.GetString("GoBackTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Connect.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Provided key is invalid. Please check again key displayed in-game..
        /// </summary>
        public static string InvalidKey {
            get {
                return ResourceManager.GetString("InvalidKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Code has expired. Please scan again QR Code available in-game..
        /// </summary>
        public static string InvalidQrCode {
            get {
                return ResourceManager.GetString("InvalidQrCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Privacy.
        /// </summary>
        public static string Privacy {
            get {
                return ResourceManager.GetString("Privacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Blue Force Tracking.
        /// </summary>
        public static string STR_ctab_core_aceMenu {
            get {
                return ResourceManager.GetString("STR_ctab_core_aceMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à GD300 Android.
        /// </summary>
        public static string STR_ctab_core_Android {
            get {
                return ResourceManager.GetString("STR_ctab_core_Android", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à GD300 Rugged Wearable Computer.
        /// </summary>
        public static string STR_ctab_core_AndroidShort {
            get {
                return ResourceManager.GetString("STR_ctab_core_AndroidShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Armor.
        /// </summary>
        public static string STR_ctab_core_ArmorMenu {
            get {
                return ResourceManager.GetString("STR_ctab_core_ArmorMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à AT.
        /// </summary>
        public static string STR_ctab_core_ATMenu {
            get {
                return ResourceManager.GetString("STR_ctab_core_ATMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à At each synchronization.
        /// </summary>
        public static string STR_ctab_core_atSync {
            get {
                return ResourceManager.GetString("STR_ctab_core_atSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Battalion Aid Station.
        /// </summary>
        public static string STR_ctab_core_BASHint {
            get {
                return ResourceManager.GetString("STR_ctab_core_BASHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à BAS.
        /// </summary>
        public static string STR_ctab_core_BASMenu {
            get {
                return ResourceManager.GetString("STR_ctab_core_BASMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Blue Force Tracking.
        /// </summary>
        public static string STR_ctab_core_bft_mode {
            get {
                return ResourceManager.GetString("STR_ctab_core_bft_mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Allow tracking of units equiped with cTab items. Position may be updated at each synchronization, or can be real time.
        /// </summary>
        public static string STR_ctab_core_bft_modeDetails {
            get {
                return ResourceManager.GetString("STR_ctab_core_bft_modeDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Blue Force Tracker - Quick Key.
        /// </summary>
        public static string STR_ctab_core_BFTF1Hint {
            get {
                return ResourceManager.GetString("STR_ctab_core_BFTF1Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à FBCB2 - Blue Force Tracker.
        /// </summary>
        public static string STR_ctab_core_BFTIconHint {
            get {
                return ResourceManager.GetString("STR_ctab_core_BFTIconHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Group call sign.
        /// </summary>
        public static string STR_ctab_core_callSign {
            get {
                return ResourceManager.GetString("STR_ctab_core_callSign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Casualty.
        /// </summary>
        public static string STR_ctab_core_CasualtyMenu {
            get {
                return ResourceManager.GetString("STR_ctab_core_CasualtyMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Casualty Collection Point.
        /// </summary>
        public static string STR_ctab_core_CCPHint {
            get {
                return ResourceManager.GetString("STR_ctab_core_CCPHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à CCP.
        /// </summary>
        public static string STR_ctab_core_CCPMenu {
            get {
                return ResourceManager.GetString("STR_ctab_core_CCPMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Center Map.
        /// </summary>
        public static string STR_ctab_core_CenterMap {
            get {
                return ResourceManager.GetString("STR_ctab_core_CenterMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Center Map On Current Position (F7).
        /// </summary>
        public static string STR_ctab_core_CenterMapHint {
            get {
                return ResourceManager.GetString("STR_ctab_core_CenterMapHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Close Interface.
        /// </summary>
        public static string STR_ctab_core_CloseInterfaceHint {
            get {
                return ResourceManager.GetString("STR_ctab_core_CloseInterfaceHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Compose &gt;&gt;.
        /// </summary>
        public static string STR_ctab_core_ComposeMessage {
            get {
                return ResourceManager.GetString("STR_ctab_core_ComposeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Compose Messages.
        /// </summary>
        public static string STR_ctab_core_ComposeMessageHint {
            get {
                return ResourceManager.GetString("STR_ctab_core_ComposeMessageHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Compose Message.
        /// </summary>
        public static string STR_ctab_core_ComposeMessageTitle {
            get {
                return ResourceManager.GetString("STR_ctab_core_ComposeMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Configure GD300 Android.
        /// </summary>
        public static string STR_ctab_core_ConfigureAndroid {
            get {
                return ResourceManager.GetString("STR_ctab_core_ConfigureAndroid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Configure MicroDAGR.
        /// </summary>
        public static string STR_ctab_core_ConfigureMicroDAGR {
            get {
                return ResourceManager.GetString("STR_ctab_core_ConfigureMicroDAGR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Configure TAD.
        /// </summary>
        public static string STR_ctab_core_ConfigureTAD {
            get {
                return ResourceManager.GetString("STR_ctab_core_ConfigureTAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Decrease Brightness.
        /// </summary>
        public static string STR_ctab_core_DecreaseBrightnessHint {
            get {
                return ResourceManager.GetString("STR_ctab_core_DecreaseBrightnessHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Decrease Font.
        /// </summary>
        public static string STR_ctab_core_DecreaseFontHint {
            get {
                return ResourceManager.GetString("STR_ctab_core_DecreaseFontHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete.
        /// </summary>
        public static string STR_ctab_core_DeleteMessage {
            get {
                return ResourceManager.GetString("STR_ctab_core_DeleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete Selected Message(s).
        /// </summary>
        public static string STR_ctab_core_DeleteMessageHint {
            get {
                return ResourceManager.GetString("STR_ctab_core_DeleteMessageHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Disabled.
        /// </summary>
        public static string STR_ctab_core_disabled {
            get {
                return ResourceManager.GetString("STR_ctab_core_disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Display/Hide.
        /// </summary>
        public static string STR_ctab_core_DisplayHide {
            get {
                return ResourceManager.GetString("STR_ctab_core_DisplayHide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à E .
        /// </summary>
        public static string STR_ctab_core_East {
            get {
                return ResourceManager.GetString("STR_ctab_core_East", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enabled.
        /// </summary>
        public static string STR_ctab_core_enabled {
            get {
                return ResourceManager.GetString("STR_ctab_core_enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enemy SALUTE.
        /// </summary>
        public static string STR_ctab_core_EnemyMenu {
            get {
                return ResourceManager.GetString("STR_ctab_core_EnemyMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à FBCB2.
        /// </summary>
        public static string STR_ctab_core_FBCB2 {
            get {
                return ResourceManager.GetString("STR_ctab_core_FBCB2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à General.
        /// </summary>
        public static string STR_ctab_core_GeneralMenu {
            get {
                return ResourceManager.GetString("STR_ctab_core_GeneralMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Helmet Camera.
        /// </summary>
        public static string STR_ctab_core_HCam {
            get {
                return ResourceManager.GetString("STR_ctab_core_HCam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à HD Helmet Mounted Camera.
        /// </summary>
        public static string STR_ctab_core_HCamShort {
            get {
                return ResourceManager.GetString("STR_ctab_core_HCamShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Helicopter.
        /// </summary>
        public static string STR_ctab_core_HelicopterMenu {
            get {
                return ResourceManager.GetString("STR_ctab_core_HelicopterMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Helmet cam.
        /// </summary>
        public static string STR_ctab_core_helmetcam_mode {
            get {
                return ResourceManager.GetString("STR_ctab_core_helmetcam_mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Allow usage of helmet cam on tablet.
        /// </summary>
        public static string STR_ctab_core_helmetcam_modeDetails {
            get {
                return ResourceManager.GetString("STR_ctab_core_helmetcam_modeDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Helmet Cam Live Feed - Quick Key.
        /// </summary>
        public static string STR_ctab_core_HelmetCamF3Hint {
            get {
                return ResourceManager.GetString("STR_ctab_core_HelmetCamF3Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Live Helmet Cam Video Feeds.
        /// </summary>
        public static string STR_ctab_core_HelmetCamIconHint {
            get {
                return ResourceManager.GetString("STR_ctab_core_HelmetCamIconHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Toggle Map (F1) / Messages (F4).
        /// </summary>
        public static string STR_ctab_core_HomeAndroidHint {
            get {
                return ResourceManager.GetString("STR_ctab_core_HomeAndroidHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Main Menu.
        /// </summary>
        public static string STR_ctab_core_HomeTabletHint {
            get {
                return ResourceManager.GetString("STR_ctab_core_HomeTabletHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à left-click: Toggle DAY / NIGHT mode; right-click: Close interface.
        /// </summary>
        public static string STR_ctab_core_HomeTADHint {
            get {
                return ResourceManager.GetString("STR_ctab_core_HomeTADHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Headquaters.
        /// </summary>
        public static string STR_ctab_core_HQHint {
            get {
                return ResourceManager.GetString("STR_ctab_core_HQHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à HQ.
        /// </summary>
        public static string STR_ctab_core_HQMenu {
            get {
                return ResourceManager.GetString("STR_ctab_core_HQMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Toggle Main Interface.
        /// </summary>
        public static string STR_ctab_core_ifMain {
            get {
                return ResourceManager.GetString("STR_ctab_core_ifMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Open cTab device in small overlay mode if available.
        /// </summary>
        public static string STR_ctab_core_ifMainDetails {
            get {
                return ResourceManager.GetString("STR_ctab_core_ifMainDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Toggle Secondary Interface.
        /// </summary>
        public static string STR_ctab_core_ifSecondary {
            get {
                return ResourceManager.GetString("STR_ctab_core_ifSecondary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Open cTab device in interactable mode (fullscreen).
        /// </summary>
        public static string STR_ctab_core_ifSecondaryDetails {
            get {
                return ResourceManager.GetString("STR_ctab_core_ifSecondaryDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Toggle Main Tertiary.
        /// </summary>
        public static string STR_ctab_core_ifTertiary {
            get {
                return ResourceManager.GetString("STR_ctab_core_ifTertiary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Open private cTab device when in a vehicle with its own cTab device, or to open Tablet while also carrying a MicroDAGR.
        /// </summary>
        public static string STR_ctab_core_ifTertiaryDetails {
            get {
                return ResourceManager.GetString("STR_ctab_core_ifTertiaryDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Read Message.
        /// </summary>
        public static string STR_ctab_core_InboxTitle {
            get {
                return ResourceManager.GetString("STR_ctab_core_InboxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Increase Brightness.
        /// </summary>
        public static string STR_ctab_core_IncreaseBrightnessHint {
            get {
                return ResourceManager.GetString("STR_ctab_core_IncreaseBrightnessHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Increase Font.
        /// </summary>
        public static string STR_ctab_core_IncreaseFontHint {
            get {
                return ResourceManager.GetString("STR_ctab_core_IncreaseFontHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Infantry.
        /// </summary>
        public static string STR_ctab_core_InfantryMenu {
            get {
                return ResourceManager.GetString("STR_ctab_core_InfantryMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Loading....
        /// </summary>
        public static string STR_ctab_core_Loading {
            get {
                return ResourceManager.GetString("STR_ctab_core_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Landing Zone.
        /// </summary>
        public static string STR_ctab_core_LZHint {
            get {
                return ResourceManager.GetString("STR_ctab_core_LZHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à LZ.
        /// </summary>
        public static string STR_ctab_core_LZMenu {
            get {
                return ResourceManager.GetString("STR_ctab_core_LZMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Map Options.
        /// </summary>
        public static string STR_ctab_core_MapOptionsHint {
            get {
                return ResourceManager.GetString("STR_ctab_core_MapOptionsHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Map Textures.
        /// </summary>
        public static string STR_ctab_core_MapTextures {
            get {
                return ResourceManager.GetString("STR_ctab_core_MapTextures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Toggle Map Textures (F6).
        /// </summary>
        public static string STR_ctab_core_MapTexturesHint {
            get {
                return ResourceManager.GetString("STR_ctab_core_MapTexturesHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Map Tools.
        /// </summary>
        public static string STR_ctab_core_MapTools {
            get {
                return ResourceManager.GetString("STR_ctab_core_MapTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Toggle Map Tools (F5).
        /// </summary>
        public static string STR_ctab_core_MapToolsHint {
            get {
                return ResourceManager.GetString("STR_ctab_core_MapToolsHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Marker added succesfully.
        /// </summary>
        public static string STR_ctab_core_markerAdded {
            get {
                return ResourceManager.GetString("STR_ctab_core_markerAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mass Casualty Incident.
        /// </summary>
        public static string STR_ctab_core_MCIHint {
            get {
                return ResourceManager.GetString("STR_ctab_core_MCIHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à MCI.
        /// </summary>
        public static string STR_ctab_core_MCIMenu {
            get {
                return ResourceManager.GetString("STR_ctab_core_MCIMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Equipped with APCs/IFVs.
        /// </summary>
        public static string STR_ctab_core_MechInfHint {
            get {
                return ResourceManager.GetString("STR_ctab_core_MechInfHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mechanized Inf.
        /// </summary>
        public static string STR_ctab_core_MechInfMenu {
            get {
                return ResourceManager.GetString("STR_ctab_core_MechInfMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Medical.
        /// </summary>
        public static string STR_ctab_core_MedicalMenu {
            get {
                return ResourceManager.GetString("STR_ctab_core_MedicalMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à [Cancel].
        /// </summary>
        public static string STR_ctab_core_MenuExit {
            get {
                return ResourceManager.GetString("STR_ctab_core_MenuExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Text Message Application - Quick Key.
        /// </summary>
        public static string STR_ctab_core_MessageF4Hint {
            get {
                return ResourceManager.GetString("STR_ctab_core_MessageF4Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Text Messaging System.
        /// </summary>
        public static string STR_ctab_core_MessageIconHint {
            get {
                return ResourceManager.GetString("STR_ctab_core_MessageIconHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Your message has been sent..
        /// </summary>
        public static string STR_ctab_core_MessageSent {
            get {
                return ResourceManager.GetString("STR_ctab_core_MessageSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à MG.
        /// </summary>
        public static string STR_ctab_core_MGMenu {
            get {
                return ResourceManager.GetString("STR_ctab_core_MGMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à MicroDAGR.
        /// </summary>
        public static string STR_ctab_core_MicroDAGR {
            get {
                return ResourceManager.GetString("STR_ctab_core_MicroDAGR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à HNV-2930 Micro Defense Advanced GPS Receiver.
        /// </summary>
        public static string STR_ctab_core_MicroDAGRShort {
            get {
                return ResourceManager.GetString("STR_ctab_core_MicroDAGRShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mortar.
        /// </summary>
        public static string STR_ctab_core_MortarMenu {
            get {
                return ResourceManager.GetString("STR_ctab_core_MortarMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Equipped with un-protected vehicles.
        /// </summary>
        public static string STR_ctab_core_MotoInfHint {
            get {
                return ResourceManager.GetString("STR_ctab_core_MotoInfHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Motorized Inf.
        /// </summary>
        public static string STR_ctab_core_MotoInfMenu {
            get {
                return ResourceManager.GetString("STR_ctab_core_MotoInfMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à New marker at #%1.
        /// </summary>
        public static string STR_ctab_core_newMarker {
            get {
                return ResourceManager.GetString("STR_ctab_core_newMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à New message from %1.
        /// </summary>
        public static string STR_ctab_core_newMessage {
            get {
                return ResourceManager.GetString("STR_ctab_core_newMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No Message Selected.
        /// </summary>
        public static string STR_ctab_core_NoMessageSelected {
            get {
                return ResourceManager.GetString("STR_ctab_core_NoMessageSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à N .
        /// </summary>
        public static string STR_ctab_core_North {
            get {
                return ResourceManager.GetString("STR_ctab_core_North", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à NE.
        /// </summary>
        public static string STR_ctab_core_NorthEast {
            get {
                return ResourceManager.GetString("STR_ctab_core_NorthEast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à NW.
        /// </summary>
        public static string STR_ctab_core_NorthWest {
            get {
                return ResourceManager.GetString("STR_ctab_core_NorthWest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Plane.
        /// </summary>
        public static string STR_ctab_core_PlaneMenu {
            get {
                return ResourceManager.GetString("STR_ctab_core_PlaneMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 25–40 personnels.
        /// </summary>
        public static string STR_ctab_core_PlatoonHint {
            get {
                return ResourceManager.GetString("STR_ctab_core_PlatoonHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Platoon •••.
        /// </summary>
        public static string STR_ctab_core_PlatoonMenu {
            get {
                return ResourceManager.GetString("STR_ctab_core_PlatoonMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Read &gt;&gt;.
        /// </summary>
        public static string STR_ctab_core_ReadMessages {
            get {
                return ResourceManager.GetString("STR_ctab_core_ReadMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Read Messages.
        /// </summary>
        public static string STR_ctab_core_ReadMessagesHint {
            get {
                return ResourceManager.GetString("STR_ctab_core_ReadMessagesHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Real time.
        /// </summary>
        public static string STR_ctab_core_realTime {
            get {
                return ResourceManager.GetString("STR_ctab_core_realTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rifle.
        /// </summary>
        public static string STR_ctab_core_RifleMenu {
            get {
                return ResourceManager.GetString("STR_ctab_core_RifleMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 7–13 personnels.
        /// </summary>
        public static string STR_ctab_core_SectionHint {
            get {
                return ResourceManager.GetString("STR_ctab_core_SectionHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Section ••.
        /// </summary>
        public static string STR_ctab_core_SectionMenu {
            get {
                return ResourceManager.GetString("STR_ctab_core_SectionMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Send.
        /// </summary>
        public static string STR_ctab_core_SendMessage {
            get {
                return ResourceManager.GetString("STR_ctab_core_SendMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Singular.
        /// </summary>
        public static string STR_ctab_core_SingularMenu {
            get {
                return ResourceManager.GetString("STR_ctab_core_SingularMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Icon Size -.
        /// </summary>
        public static string STR_ctab_core_SizeDown {
            get {
                return ResourceManager.GetString("STR_ctab_core_SizeDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Decrease Icon/Text Size.
        /// </summary>
        public static string STR_ctab_core_SizeDownHint {
            get {
                return ResourceManager.GetString("STR_ctab_core_SizeDownHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Icon Size +.
        /// </summary>
        public static string STR_ctab_core_SizeUp {
            get {
                return ResourceManager.GetString("STR_ctab_core_SizeUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Increase Icon/Text Size.
        /// </summary>
        public static string STR_ctab_core_SizeUpHint {
            get {
                return ResourceManager.GetString("STR_ctab_core_SizeUpHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à S .
        /// </summary>
        public static string STR_ctab_core_South {
            get {
                return ResourceManager.GetString("STR_ctab_core_South", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à SE.
        /// </summary>
        public static string STR_ctab_core_SouthEast {
            get {
                return ResourceManager.GetString("STR_ctab_core_SouthEast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à SW.
        /// </summary>
        public static string STR_ctab_core_SouthWest {
            get {
                return ResourceManager.GetString("STR_ctab_core_SouthWest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 5–10 personnels.
        /// </summary>
        public static string STR_ctab_core_SquadHint {
            get {
                return ResourceManager.GetString("STR_ctab_core_SquadHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Squad •.
        /// </summary>
        public static string STR_ctab_core_SquadMenu {
            get {
                return ResourceManager.GetString("STR_ctab_core_SquadMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Static AA.
        /// </summary>
        public static string STR_ctab_core_StaticAAMenu {
            get {
                return ResourceManager.GetString("STR_ctab_core_StaticAAMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Static AT.
        /// </summary>
        public static string STR_ctab_core_StaticATMenu {
            get {
                return ResourceManager.GetString("STR_ctab_core_StaticATMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Static MG.
        /// </summary>
        public static string STR_ctab_core_StaticMGMenu {
            get {
                return ResourceManager.GetString("STR_ctab_core_StaticMGMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Stationary.
        /// </summary>
        public static string STR_ctab_core_StationaryMenu {
            get {
                return ResourceManager.GetString("STR_ctab_core_StationaryMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Synchronization rate.
        /// </summary>
        public static string STR_ctab_core_sync_time {
            get {
                return ResourceManager.GetString("STR_ctab_core_sync_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Time required to discover new devices and units.
        /// </summary>
        public static string STR_ctab_core_sync_timeDetails {
            get {
                return ResourceManager.GetString("STR_ctab_core_sync_timeDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rugged Tablet.
        /// </summary>
        public static string STR_ctab_core_Tablet {
            get {
                return ResourceManager.GetString("STR_ctab_core_Tablet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à DK10 Rugged Tablet PC.
        /// </summary>
        public static string STR_ctab_core_TabletShort {
            get {
                return ResourceManager.GetString("STR_ctab_core_TabletShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à TAD.
        /// </summary>
        public static string STR_ctab_core_TAD {
            get {
                return ResourceManager.GetString("STR_ctab_core_TAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 3–5 personnels.
        /// </summary>
        public static string STR_ctab_core_TeamHint {
            get {
                return ResourceManager.GetString("STR_ctab_core_TeamHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fireteam Ø.
        /// </summary>
        public static string STR_ctab_core_TeamMenu {
            get {
                return ResourceManager.GetString("STR_ctab_core_TeamMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Technical Data.
        /// </summary>
        public static string STR_ctab_core_techData {
            get {
                return ResourceManager.GetString("STR_ctab_core_techData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Text On/Off.
        /// </summary>
        public static string STR_ctab_core_TextOnOff {
            get {
                return ResourceManager.GetString("STR_ctab_core_TextOnOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Toggle Text on/off.
        /// </summary>
        public static string STR_ctab_core_TextOnOffHint {
            get {
                return ResourceManager.GetString("STR_ctab_core_TextOnOffHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Toggle Fullscreen.
        /// </summary>
        public static string STR_ctab_core_toggleFullscreen {
            get {
                return ResourceManager.GetString("STR_ctab_core_toggleFullscreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Toggle Interface Position.
        /// </summary>
        public static string STR_ctab_core_toggleIfPosition {
            get {
                return ResourceManager.GetString("STR_ctab_core_toggleIfPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Toggle overlay mode interface position from left to right or reset interactive mode interface position to default.
        /// </summary>
        public static string STR_ctab_core_toggleIfPositionDetails {
            get {
                return ResourceManager.GetString("STR_ctab_core_toggleIfPositionDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à UAV feed.
        /// </summary>
        public static string STR_ctab_core_uav_mode {
            get {
                return ResourceManager.GetString("STR_ctab_core_uav_mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Allow usage of UAV feed on tablet.
        /// </summary>
        public static string STR_ctab_core_uav_modeDetails {
            get {
                return ResourceManager.GetString("STR_ctab_core_uav_modeDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à UAV Intel Live Feed - Quick Key.
        /// </summary>
        public static string STR_ctab_core_UAVF2Hint {
            get {
                return ResourceManager.GetString("STR_ctab_core_UAVF2Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à UAV Video Feeds.
        /// </summary>
        public static string STR_ctab_core_UAVIconHint {
            get {
                return ResourceManager.GetString("STR_ctab_core_UAVIconHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lock UAV Cam to this position, a UAV has to be previously selected.
        /// </summary>
        public static string STR_ctab_core_UAVLockHint {
            get {
                return ResourceManager.GetString("STR_ctab_core_UAVLockHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lock UAV Cam.
        /// </summary>
        public static string STR_ctab_core_UAVLockMenu {
            get {
                return ResourceManager.GetString("STR_ctab_core_UAVLockMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unknown.
        /// </summary>
        public static string STR_ctab_core_UnknownMenu {
            get {
                return ResourceManager.GetString("STR_ctab_core_UnknownMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add Blue Force Tracking to ACE MicroDAGR.
        /// </summary>
        public static string STR_ctab_core_useAceMicroDagr {
            get {
                return ResourceManager.GetString("STR_ctab_core_useAceMicroDagr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Display Blue Force Tracking informatos on ACE MicroDAGR, and includes personnels equiped with it to tracking.
        /// </summary>
        public static string STR_ctab_core_useAceMicroDagrDetails {
            get {
                return ResourceManager.GetString("STR_ctab_core_useAceMicroDagrDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unit of heading/compass.
        /// </summary>
        public static string STR_ctab_core_useMils {
            get {
                return ResourceManager.GetString("STR_ctab_core_useMils", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Degrees (0-360).
        /// </summary>
        public static string STR_ctab_core_useMils_false {
            get {
                return ResourceManager.GetString("STR_ctab_core_useMils_false", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mils (0-6400).
        /// </summary>
        public static string STR_ctab_core_useMils_true {
            get {
                return ResourceManager.GetString("STR_ctab_core_useMils_true", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unit of heading/compass displayed in cTab devices.
        /// </summary>
        public static string STR_ctab_core_useMilsDetails {
            get {
                return ResourceManager.GetString("STR_ctab_core_useMilsDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à View Gunner Optics.
        /// </summary>
        public static string STR_ctab_core_viewGunnerOptics {
            get {
                return ResourceManager.GetString("STR_ctab_core_viewGunnerOptics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à W .
        /// </summary>
        public static string STR_ctab_core_West {
            get {
                return ResourceManager.GetString("STR_ctab_core_West", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Zoom In.
        /// </summary>
        public static string STR_ctab_core_zoomIn {
            get {
                return ResourceManager.GetString("STR_ctab_core_zoomIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Zoom In on map while cTab is in small overlay mode.
        /// </summary>
        public static string STR_ctab_core_zoomInDetails {
            get {
                return ResourceManager.GetString("STR_ctab_core_zoomInDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Zoom Out.
        /// </summary>
        public static string STR_ctab_core_zoomOut {
            get {
                return ResourceManager.GetString("STR_ctab_core_zoomOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Zoom Out on map while cTab is in small overlay mode.
        /// </summary>
        public static string STR_ctab_core_zoomOutDetails {
            get {
                return ResourceManager.GetString("STR_ctab_core_zoomOutDetails", resourceCulture);
            }
        }
    }
}
