name: .NET Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Publish Linux/ReleaseCloud
      run: dotnet publish --no-self-contained -f net8.0 -r linux-x64 -c ReleaseCloud cTabIRL/cTabWebApp/cTabWebApp.csproj -o OutputLinux
    
    - name: Publish Windows/ReleaseSolo
      run: dotnet publish --no-self-contained -f net8.0 -r win-x64 -c Release cTabIRL/cTabWebApp/cTabWebApp.csproj -o OutputWindows
     