name: .NET Release

on:
  release:
    types: [ "published" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Publish Linux x64/ReleaseCloud 
      run: dotnet publish --no-self-contained -f net8.0 -r linux-x64 -c ReleaseCloud cTabIRL/cTabWebApp/cTabWebApp.csproj -o ctab-webapp-linux-x64
      
    - name: Zip Linux x64/ReleaseCloud 
      run: zip -r ctab-webapp-linux-x64.zip ctab-webapp-linux-x64
      
    - name: Publish Linux arm64/ReleaseCloud 
      run: dotnet publish --no-self-contained -f net8.0 -r linux-arm64 -c ReleaseCloud cTabIRL/cTabWebApp/cTabWebApp.csproj -o ctab-webapp-linux-arm64

    - name: Zip Linux arm64/ReleaseCloud 
      run: zip -r ctab-webapp-linux-arm64.zip ctab-webapp-linux-arm64

    - name: Publish Windows/ReleaseSolo
      run: dotnet publish --no-self-contained -f net8.0 -r win-x64 -c Release cTabIRL/cTabWebApp/cTabWebApp.csproj -o ctab-webapp-single-user-win-x64
      
    - name: Zip Windows/ReleaseSolo
      run: zip -r ctab-webapp-single-user-win-x64.zip ctab-webapp-single-user-win-x64
      
    - uses: Shopify/upload-to-release@master
      with:
        name: ctab-webapp-linux-x64.zip
        path: "ctab-webapp-linux-x64.zip"
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        content-type: application/zip

    - uses: Shopify/upload-to-release@master
      with:
        name: ctab-webapp-linux-arm64.zip
        path: "ctab-webapp-linux-arm64.zip"
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        content-type: application/zip
        
    - uses: Shopify/upload-to-release@master
      with:
        name: ctab-webapp-single-user-win-x64.zip
        path: "ctab-webapp-single-user-win-x64.zip"
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        content-type: application/zip
        
        